version: '{build}'
configuration: Release
platform: Any CPU
image: Visual Studio 2022
before_build:
- cmd: nuget restore

build_script:
- ps: |
    $env:DevenvPath = 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE'
- '"%DevenvPath%\devenv.com" DoomLauncher.sln /build Release /project Setup\Setup.vdproj /projectconfig Release /Out errorFile.txt'
- msbuild DoomLauncher.sln /target:UnitTest /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test:
    on

after_build:
- '%APPVEYOR_BUILD_FOLDER%\DoomLauncherRelease\bin\Release\DoomLauncherRelease.exe %APPVEYOR_BUILD_FOLDER%'

artifacts:
  path: ReleaseBuild/DoomLauncher*.zip
  name: BuiltZip
  